src/Grub/PronosticsBundle/Entity/Game.php
<?php

namespace Grub\PronosticsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="prono_game")
 * @ORM\Entity(repositoryClass="Grub\PronosticsBundle\Repository\GameRepository")
 */
class Game
{

    const NOT_STARTED = 'Pas commencé',
        IN_PROGRESS = 'Match en cours',
        FINISHED = 'Terminé';

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Team", inversedBy="gamesAsTeamA", fetch="EAGER")
     * @ORM\JoinColumn(name="teamA_id", referencedColumnName="id", nullable=true)
     */
    protected $teamA;

    /**
     * @ORM\ManyToOne(targetEntity="Team", inversedBy="gamesAsTeamB", fetch="EAGER")
     * @ORM\JoinColumn(name="teamB_id", referencedColumnName="id", nullable=true)
     */
    protected $teamB;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $title;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     */
    protected $scoreA;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     */
    protected $scoreB;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date;

    /**
     * @ORM\Column(type="string")
     */
    protected $location;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $risquette;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $risquetteValidee;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $channel;

    /**
     * @ORM\OneToMany(targetEntity="Bet", mappedBy="game")
     */
    protected $bets;

    public function __toString()
    {
        return $this->title;
    }

    public function getStatus()
    {
        if (new \DateTime() > $this->getDate()) {
            if ($this->getScoreA() !== NULL && $this->getScoreB() !== NULL) {
                return self::FINISHED;
            } else {
                return self::IN_PROGRESS;
            }
        } else {
            return self::NOT_STARTED;
        }
    }

    public function __construct()
    {
        $this->bets = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set scoreA
     *
     * @param integer $scoreA
     */
    public function setScoreA($scoreA)
    {
        $this->scoreA = $scoreA;
    }

    /**
     * Get scoreA
     *
     * @return integer
     */
    public function getScoreA()
    {
        return $this->scoreA;
    }

    /**
     * Set scoreB
     *
     * @param integer $scoreB
     */
    public function setScoreB($scoreB)
    {
        $this->scoreB = $scoreB;
    }

    /**
     * Get scoreB
     *
     * @return integer
     */
    public function getScoreB()
    {
        return $this->scoreB;
    }

    /**
     * Set date
     *
     * @param datetime $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * Get date
     *
     * @return datetime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set location
     *
     * @param string $location
     */
    public function setLocation($location)
    {
        $this->location = $location;
    }

    /**
     * Get location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set risquette
     *
     * @param text $risquette
     */
    public function setRisquette($risquette)
    {
        $this->risquette = $risquette;
    }

    /**
     * Get risquette
     *
     * @return text
     */
    public function getRisquette()
    {
        return $this->risquette;
    }

    /**
     * Set risquetteValidee
     *
     * @param boolean $risquetteValidee
     */
    public function setRisquetteValidee($risquetteValidee)
    {
        $this->risquetteValidee = $risquetteValidee;
    }

    /**
     * Get risquetteValidee
     *
     * @return boolean
     */
    public function getRisquetteValidee()
    {
        return $this->risquetteValidee;
    }

    /**
     * Set teamA
     *
     * @param Grub\PronosticsBundle\Entity\Team $teamA
     */
    public function setTeamA(\Grub\PronosticsBundle\Entity\Team $teamA)
    {
        $this->teamA = $teamA;
    }

    /**
     * Get teamA
     *
     * @return Grub\PronosticsBundle\Entity\Team
     */
    public function getTeamA()
    {
        return $this->teamA;
    }

    /**
     * Set teamB
     *
     * @param Grub\PronosticsBundle\Entity\Team $teamB
     */
    public function setTeamB(\Grub\PronosticsBundle\Entity\Team $teamB)
    {
        $this->teamB = $teamB;
    }

    /**
     * Get teamB
     *
     * @return Grub\PronosticsBundle\Entity\Team
     */
    public function getTeamB()
    {
        return $this->teamB;
    }

    /**
     * Add bets
     *
     * @param Grub\PronosticsBundle\Entity\Bet $bets
     */
    public function addBet(\Grub\PronosticsBundle\Entity\Bet $bets)
    {
        $this->bets[] = $bets;
    }

    /**
     * Get bets
     *
     * @return Doctrine\Common\Collections\Collection
     */
    public function getBets()
    {
        return $this->bets;
    }

    /**
     * Set channel
     *
     * @param string $channel
     */
    public function setChannel($channel)
    {
        $this->channel = $channel;
    }

    /**
     * Get channel
     *
     * @return string 
     */
    public function getChannel()
    {
        return $this->channel;
    }
}

src/Grub/PronosticsBundle/Controller/DefaultController.php
<?php

namespace Grub\PronosticsBundle\Controller;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\FormError;
use Grub\PronosticsBundle\Form\BetType;
use Grub\PronosticsBundle\Entity\Game;
use Grub\PronosticsBundle\Entity\Bet;


class DefaultController extends Controller
{

    public function accueilAction(Request $request)
    {
        return $this->render('GrubPronosticsBundle:Default:accueil.html.twig');
    }

    public function pronostiquerAction(Request $request)
    {
        $user = $this->getUser();

        $em = $this->get('doctrine.orm.entity_manager');
        $games = $em->getRepository('GrubPronosticsBundle:Game')->findJoinedToTeamAndBetByUser($user->getId());

        return $this->render('GrubPronosticsBundle:Default:pronostiquer.html.twig',
            array('games' => $games));
    }

    public function envoyerPronostiqueAction(Request $request, $gameId)
    {
        $user = $this->getUser();

        $em = $this->get('doctrine.orm.entity_manager');
        $game = $em->getRepository('GrubPronosticsBundle:Game')->findOneJoinedToTeamAndBetByUser($gameId, $user->getId());

        if (!$game) {
            throw $this->createNotFoundException('Impossible de trouver le match');
        }

        if ($game->getBets()->count() === 1) {
            $bet = $game->getBets()->first();
        } else {
            $bet = new Bet();
            $bet->setGame($game);
            $bet->setUser($user);
        }

        $form = $this->createForm(new BetType(), $bet);

        $form->handleRequest($request);

        $this->get('session')->getFlashBag()->get('message-ok');
        if ($game->getStatus() == Game::IN_PROGRESS) {
            $form->addError(new FormError('Désolé, le match est déjà commencé :-('));
        } else if ($game->getStatus() == Game::FINISHED) {
            $form->addError(new FormError('Désolé, le match est terminé :-('));
        } else {
            if ($form->isValid()) {
                $em->persist($bet);
                $em->flush();
                $this->get('session')->getFlashBag()->add('message-ok', 'Pronostique enregistré :-)');
            }
        }

        return $this->render('GrubPronosticsBundle:Default:game.html.twig',
            array('game' => $game, 'bet' => $bet, 'form' => $form->createView()));
    }

    public function classementAction(Request $request)
    {
        if (!is_object($this->getUser())) {
            throw new AccessDeniedException('interdit');
        }

        $em = $this->get('doctrine.orm.entity_manager');
        $users = $em->getRepository('GrubUserBundle:User')->findAllJoinedToBet($this->getUser()->getGroup()->getId());

        foreach ($users as $user) {
            $classement[$user->getId()] = $user->getRankingInfos();
        }

        uasort($classement, array($this, "cmpGlobal"));
        $this->applyClassement($classement, 'global', 'class');

        uasort($classement, array($this, "cmpGlobalRisq"));
        $this->applyClassement($classement, 'globalrisq', 'classrisq');

        uasort($classement, array($this, "cmpGlobalSansRisq"));
        $this->applyClassement($classement, 'globalsansrisq', 'classsansrisq');

        return $this->render('GrubPronosticsBundle:Default:classement.html.twig',
            array('classement' => $classement));
    }

    static function cmpGlobal($a, $b)
    {
        if ($a['global'] == $b['global']) {
            return 0;
        }
        return ($a['global'] > $b['global']) ? -1 : 1;
    }

    static function cmpGlobalRisq($a, $b)
    {
        if ($a['globalrisq'] == $b['globalrisq']) {
            return 0;
        }
        return ($a['globalrisq'] > $b['globalrisq']) ? -1 : 1;
    }

    static function cmpGlobalSansRisq($a, $b)
    {
        if ($a['globalsansrisq'] == $b['globalsansrisq']) {
            return 0;
        }
        return ($a['globalsansrisq'] > $b['globalsansrisq']) ? -1 : 1;
    }

    public function applyClassement(&$classement, $scoreKey, $classementKey)
    {
        $i = 0;
        $ii = 0;
        $lastScore = null;
        foreach ($classement as &$classementUser) {
            if ($lastScore != $classementUser[$scoreKey]) {
                $i += 1 + $ii;
                $ii = 0;
            } else {
                $ii += 1;
            }
            $lastScore = $classementUser[$scoreKey];
            $classementUser[$classementKey] = $i;

        }
    }

    public function groupesAction(Request $request)
    {
//        $em = $this->container->get('doctrine.orm.entity_manager');
//        $games = $em->getRepository('GrubPronosticsBundle:Game')->findAllFinishedGroupPhase();
//
//        $groups = array();
//
//        foreach ($games as $game) {
//            $scoreA = $game->getScoreA();
//            $teamA = $game->getTeamA();
//            $teamAId = $teamA->getId();
//
//            $scoreB = $game->getScoreB();
//            $teamB = $game->getTeamB();
//            $teamBId = $teamB->getId();
//
//            $grp = $teamA->getGroup();
//            $grpId = $grp->getId();
//
//            if (!array_key_exists($grpId, $groups)) {
//                $groups[$grpId] = array(
//                    'name' => $grp->getName(),
//                    'teams' => array()
//                );
//            }
//
//            $teams = &$groups[$grpId]['teams'];
//
//            if (!array_key_exists($teamAId, $teams)) {
//                $teams[$teamAId] = $this->createEmptyGroupTeamScoreBoard($teamA);
//            }
//            $this->computeGroupTeamScoreBoard($teams[$teamAId], $scoreA, $scoreB);
//
//            if (!array_key_exists($teamBId, $teams)) {
//                $teams[$teamBId] = $this->createEmptyGroupTeamScoreBoard($teamB);
//            }
//            $this->computeGroupTeamScoreBoard($teams[$teamBId], $scoreB, $scoreA);
//        }
//
//        foreach ($groups as &$grp) {
//            $grp['teams'] = array_values($grp['teams']);
//            uasort($grp['teams'], array($this, 'cmpScoreBoard'));
//        }

//        return $this->container->get('templating')->renderResponse('GrubPronosticsBundle:Default:groupes.html.twig',
//            array('groups' => $groups));

        return $this->render('GrubPronosticsBundle:Default:groupes.html.twig');
    }

    private function createEmptyGroupTeamScoreBoard($team)
    {
        return array('name' => $team->getName(),
            'pts' => 0, 'j' => 0, 'v' => 0, 'n' => 0, 'd' => 0, 'bp' => 0, 'bc' => 0, 'diff' => 0);
    }

    private function computeGroupTeamScoreBoard(&$scoreBoard, $score, $otherScore)
    {
        $scoreBoard['j']++;

        if ($score > $otherScore) {
            $scoreBoard['v']++;
        }

        if ($score === $otherScore) {
            $scoreBoard['n']++;
        }

        if ($score < $otherScore) {
            $scoreBoard['d']++;
        }

        $scoreBoard['bp']+= $score;
        $scoreBoard['bc']+= $otherScore;
        $scoreBoard['diff'] = $scoreBoard['bp'] - $scoreBoard['bc'];
        $scoreBoard['pts'] = $scoreBoard['v'] * 3 + $scoreBoard['n'];
    }

    private static function cmpScoreBoard($a, $b)
    {
        if ($a['pts'] == $b['pts']) {
            if ($a['diff'] == $b['diff']) {
                return 0;
            } else {
                return ($a['diff'] > $b['diff']) ? -1 : 1;
            }
        }
        return ($a['pts'] > $b['pts']) ? -1 : 1;
    }
}

src/Grub/PronosticsBundle/Resources/views/Default/accueil.html.twig
{% extends "GrubPronosticsBundle::layout.html.twig" %}

{% block stylesheet %}
{% stylesheets filter='cssrewrite,?yui_css' 'bundles/grubpronostics/less/accueil.less' %}
<link rel="stylesheet" href="{{ asset_url }}">
{% endstylesheets %}
{% endblock %}

{% block content %}

<h1>Bienvenue sur pronostics !</h1>

{% if not is_granted("IS_AUTHENTICATED_REMEMBERED") %}

<h2>Vous n'êtes pas connecté :-(</h2>

<p>Si vous possédez un compte, cliquez sur le lien connexion en haut à droite. Login (nom.prenom) et mot de passe
  (nom.prenom à changer rapidement).</p>
<p>Si vous ne possédez pas de compte, adressez-vous à l’un des 3 administrateurs.</p>

{% endif %}

<h2>Comment jouer ?</h2>

<h3>1. On pronostique</h3>
<p>On pronostique simplement le score du match. Si vous avez pronostiqué le bon vainqueur ou le bon match nul, 3 points
  dans la besace. Tout bon score trouvé pour 1 équipe amène 1 point supplémentaire. On gagne donc au maximum 5 points
  par match en trouvant le bon score.</p>

<h3>2. On joue le bonus risquette</h3>

<h4>Principe de la risquette</h4>
<p>Sur chaque match, il est possible de gagner jusqu'à 3 points supplémentaires en pariant sur la risquette. Le principe
  est simple : si la risquette proposée se réalise, vous gagnez votre mise, sinon vous la perdez. Exemple de risquette :
  "Henry marque au moins un but", "Au moins un tir sur un poteau dans le match", ...</p>

<h4>Risquette négative</h4>
<p>Si vous pensez que la risquette ne se réalisera pas, et bien vous pouvez miser jusqu'à 3 points d'anti-risquette. En
  gros, sur une match Brésil-Iles Féroé, si la risquette c'est "Iles Féroé atomise la brésil 18-4", et que vous pensez
  que cette risquette ne se réalisera pas (et vous aurez bien raison), et bien misez en négatif, ça vous amènera des
  points assurément !</p>
<p><em>Source de validation du bonus risquette : feuilles de matchs de <a href="http://www.sports.fr">www.sports.fr</a></em></p>

<h3>3. Suivez votre évolution</h3>
<p>Après chaque série de matchs, au niveau du tableau des scores...</p>

<h3>Consignes générales</h3>
<ul>
  <li>Valider ses pronos chaque jour le début du match.</li>
</ul>

<h3>Classement final</h3>
<p>Le vainqueur final est celui qui a le plus de points au Total (prono + risquettes)</p>
<p>Valider ses pronos chaque jour avant le dbut du match.</p>
<ul>
  <li>Si égalité, total sans risquette</li>
  <li>Si encore égalité : nombre de fois où le bon 1N2 a été trouvé</li>
  <li>Si encore égalité, vote à main levée des participants</li>
</ul>

<p>Bonne chance ;-)</p>

{% endblock %}

src/Grub/PronosticsBundle/Resources/views/Default/classement.html.twig
{% extends "GrubPronosticsBundle::layout.html.twig" %}

{% block stylesheet %}

{% stylesheets filter='cssrewrite,?yui_css' 'bundles/grubpronostics/less/classement.less' %}
<link rel="stylesheet" href="{{ asset_url }}">
{% endstylesheets %}

{% endblock %}

{% block content %}

<h1>Classement ({{ classement|length }} joueurs)</h1>

<table class="table table-striped table-bordered table-condensed classement">
  <thead>
  <tr>
    <th rowspan="3">Joueur</th>
    <th colspan="5">Points</th>
    <th colspan="3">Classement</th>
    <th colspan="4">Nombre de pronostiques</th>
  </tr>
  <tr>
    <th colspan="3">global</th>
    <th colspan="2">moyenne par pronostique</th>
    <th rowspan="2">total</th>
    <th rowspan="2">risq.</th>
    <th rowspan="2"><s>risq.</s></th>
    <th rowspan="2">total</th>
    <th rowspan="2">cartons pleins</th>
    <th rowspan="2">exacts</th>
    <th rowspan="2">à côté de la plaque</th>
  </tr>
  <tr>
    <th>tout</th>
    <th>risq.</th>
    <th><s>risq.</s></th>
    <th>risq.</th>
    <th><s>risq.</s></th>
  </tr>
  <tr class="sort">
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>

  {% set i=0 %}
  {% set score_prev=0 %}

  {% for user in classement %}

  {% set i=i+1 %}
  {% if (score_prev==user.global) %}
  {% set i=i-1 %}
  {% endif %}

  <tr {{ app.user.username == user.username ? 'class="you"' : '' }}>
    <td>{{ user.firstname }} {{ user.lastname }}</td>
    <td class="important" title="total des points">{{ user.global }}</td>
    <td title="total des points (risquettes uniquement)">{{ user.globalrisq }}</td>
    <td title="total des points (sans riquettes)">{{ user.globalsansrisq }}</td>
    <td title="moyenne des points par pronostique (avec risquettes)">{{ user.moyavecrisq }}</td>
    <td title="moyenne des points par pronostique (sans risquettes)">{{ user.moysansrisq }}</td>
    <td class="important" title="classement total">{{ user.class }}</td>
    <td title="classement (risquettes uniquement)">{{ user.classrisq }}</td>
    <td title="classement (sans risquettes)">{{ user.classsansrisq }}</td>
    <td title="Nombre de pronostiques (total)">{{ user.nb }}</td>
    <td title="Nombre de pronostiques (cartons pleins)">{{ user.carton }}</td>
    <td title="Nombre de pronostiques (exacts)">{{ user.exact }}</td>
    <td title="Nombre de pronostiques (à côté de la plaque)">{{ user.acote }}</td>
  </tr>

  {% set score_prev=user.global %}
  {% else %}
  <tr>
    <td colspan="13">Pas de joueurs</td>
  </tr>
  {% endfor%}

  </tbody>
</table>

{% endblock %}

{% block javascript %}
<script src="{{ asset('bundles/grubpronostics/js/libs/jquery-1.7.2.min.js') }}"></script>
<script src="{{ asset('bundles/grubpronostics/js/libs/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('bundles/grubpronostics/js/libs/FixedHeader.min.js') }}"></script>
{% javascripts 'bundles/grubpronostics/js/classement.js' filter='?yui_js' %} <script src="{{ asset_url }}"></script>{% endjavascripts %}
{% endblock %}

src/Grub/PronosticsBundle/Resources/views/Default/game.html.twig
{% set NOT_STARTED = constant('Grub\\PronosticsBundle\\Entity\\Game::NOT_STARTED') %}
{% set IN_PROGRESS = constant('Grub\\PronosticsBundle\\Entity\\Game::IN_PROGRESS') %}
{% set FINISHED = constant('Grub\\PronosticsBundle\\Entity\\Game::FINISHED') %}

<form action="{{ path('GrubPronosticsBundle_envoi_pronostique', { 'gameId': game.id }) }}" method="POST">
  <div class="game">
    <div class="message">
      {% if form is not null %}
        {% for flashMessage in app.session.flashbag.get('message-ok') %}
            <span class="message-ok">{{ flashMessage }}</span>
        {% endfor %}
        <div class="message-global">{{ form_errors(form) }}</div>
        <div class="message-scoreA">{{ form_errors(form.scoreA) }}</div>
        <div class="message-scoreB">{{ form_errors(form.scoreB) }}</div>
        <div class="message-risquette">{{ form_errors(form.risquette) }}</div>
      {% endif %}
    </div>

    <div class="title">{{ game.title }}</div>

    <div class="infos">
      <div class="time">{{ game.date|date("H:i") }}</div>
      {% if game.channel is not null and game.channel != "" %}
      <div class="channel"><img src="{{ asset('bundles/grubpronostics/images/channels/' ~ game.channel|slug ~ '.png') }}" alt="{{ game.channel }}"></div>
      {% endif %}
      <div class="location">{{ game.location }}</div>
    </div>

    <div class="teamA name">{{ game.teamA.name | default('...') }}</div>
    <div class="teamA flag">
      <img src="{{ asset('bundles/grubpronostics/images/flags/' ~ game.teamA|slug ~ '.png') }}" alt="{{ game.teamA }}">
    </div>

    <div class="teamB name">{{ game.teamB.name | default('...') }}</div>
    <div class="teamB flag">
      <img src="{{ asset('bundles/grubpronostics/images/flags/' ~ game.teamB|slug ~ '.png') }}" alt="{{ game.teamB }}">
    </div>

    <div class="scores">
      {% if game.status != FINISHED %}
        <input type="text" class="teamA bet-input" name="bet[scoreA]"
               value="{{ bet is not null ? bet.scoreA : '' }}" required
               title="Pronostique pour l'équipe {{ game.teamA | default('...') }}"
            {{ game.status == NOT_STARTED ? '' : 'disabled' }}>

        <input type="text" class="teamB bet-input" name="bet[scoreB]"
               value="{{ bet is not null ? bet.scoreB : '' }}" required
               title="Pronostique pour l'équipe {{ game.teamB | default('...') }}"
            {{ game.status == NOT_STARTED ? '' : 'disabled' }}>
      {% else %}
        <div class="real-scores">{{ game.scoreA }} - {{ game.scoreB }}</div>
        {% if bet is null %}
          <div class="bet-scores">pas de prono</div>
        {% else %}
          <div class="bet-scores">prono : {{ bet.scoreA }} - {{ bet.scoreB }}</div>
        {% endif %}
      {% endif %}
    </div>

    <div class="risquette-status">Risquette :
      {% if game.status == FINISHED %}
        {% if game.risquetteValidee %}
          <span class="risquette-validee">Réalisée</span>
        {% else %}
          <span class="risquette-non-validee">Non réalisée</span>
        {% endif %}
      {% endif %}
    </div>
    <div class="risquette-description">{{ game.risquette | default('(la description de la risquette sera bientôt ajoutée...)') }}</div>

    <select class="risquette-value" name="bet[risquette]"
            title="Pronostiquez ici la probabilité que l'événement décrit au dessus arrive ou non."
        {{ game.status == NOT_STARTED ? '' : 'disabled' }}>
      <option value="-3" {{ bet is not null and bet.risquette == -3 ? 'selected' : '' }}>
        Non c'est mort (-3 pts si la risquette se réalise, 3 pts sinon)
      </option>
      <option value="-2" {{ bet is not null and bet.risquette == -2 ? 'selected' : '' }}>
        Mouais j'pense pas (-2 pts si la risquette se réalise, 2 pts sinon)
      </option>
      <option value="-1" {{ bet is not null and bet.risquette == -1 ? 'selected' : '' }}>
        Bof pt'et pas (-1 pt si la risquette se réalise, 1 pt sinon)
      </option>
      <option value="0" {{ bet is null or (bet is not null and bet.risquette) == 0 ? 'selected' : '' }}>
        J'en sais rien (quoi qu'il arrive : pas de points en moins ou en plus)
      </option>
      <option value="1" {{ bet is not null and bet.risquette == 1 ? 'selected' : '' }}>
        Bof pt'et (1 pt si la risquette se réalise, -1 pt sinon)
      </option>
      <option value="2" {{ bet is not null and bet.risquette == 2 ? 'selected' : '' }}>
        Mouais y'a moyen (2 pts si la risquette se réalise, -2 pts sinon)
      </option>
      <option value="3" {{ bet is not null and bet.risquette == 3 ? 'selected' : '' }}>
        Ziva c'est sûr (3 pts si la risquette se réalise, -3 pts sinon)
      </option>
    </select>

    <div class="game-status">
      {% if game.status == NOT_STARTED %}
        {% if bet is null %}
          <input type="submit" class="btn btn-primary" value="Pronostiquer">
        {% else %}
          <input type="submit" class="btn btn-info" value="Mettre à jour">
        {% endif %}
      {% endif %}

      {% if game.status == IN_PROGRESS %}
        <span class="in-progress">{{ IN_PROGRESS }}</span>
      {% endif %}

      {% if game.status == FINISHED %}
        {% if bet is null %}
          <span title="pas de pronostique pas de points..." class="no-points">0pts</span>
        {% else %}
          <span title="score sans risquette" class="{{ bet.score > 0 ? 'positive-points' : '' }} {{ bet.score < 0 ? 'negative-points' : '' }}">{{ bet.score }} pts</span> /
          <span title="score de la risquette (uniquement)" class="{{ bet.bonus > 0 ? 'positive-points' : '' }} {{ bet.bonus < 0 ? 'negative-points' : '' }}">{{ bet.bonus }} pts</span>
        {% endif %}
      {% endif %}
    </div>
  </div>
</form>